### ISSUE TITLE
Any chance of licensing as GPLv2+?

### ISSUE THREAD

**Issue by JeremyRand** [Tagide/chrome-bit-domain-extension#6]
Hi, any chance you might be willing to license this extension as GPLv2+ (i.e. allow any of GPLv2, GPLv3, and higher versions) instead of the current GPLv2?  There's some code in your extension that would be nice to reuse in a Namecoin extension I'm working on, which is GPLv3+.

Cheers!

**Comment by Tagide** [comment]
Sure, use any code you'd like for any project.

**Comment by JeremyRand** [comment]
Thanks @Tagide .  To make sure that I'm on safe legal ground, can you push something to your README.md saying that the code is licensed under GPLv2+?

**Comment by Tagide** [comment]
Done.

**Comment by JeremyRand** [comment]
Thanks!
